### ISSUE TITLE
Unable to View Rules

### ISSUE THREAD

**Issue by Greggis** [fireeye/HXTool#10]
I am using the latest HXTool release with a controller on 5.0.0.910952.  I replaced the library with this one https://raw.githubusercontent.com/fireeye/HXTool/master/hx_lib.py

When I go to Rules/Mange Rules I get the following returned:
No data available in table

I am able to see the rules when logged directly into the controller UI.

Is this just a 5.0 API issue that I need to wait for the next HXTool version to be released?  Thank you.

**Comment by B0fH** [comment]
Hi @Greggis -
 Sanity check question: Did you restart HXTool after replacing hx_lib.py?

Thanks,
 Elazar

**Comment by Greggis** [comment]
Hi Elazar,
Yes, I made sure to restart it. One interesting thing I noticed is that I have two controllers that are both running 5.0.  I am able to view and edit rules on one with no problems, but this one is giving me this issue for some reason.

Thank you,
Greg

**Comment by Greggis** [comment]
We did some more testing to see if there was an issue with the API on the controller itself by using curl to pull a listing of the rules.  The commands were properly returning the the rule listing.  Support assisted by pulling a log in debug mode after making the request to manage rules through HXTool.  The log showed no evidence of the API request whereas they were seeing the API request in their log from their lab instance.

**Comment by B0fH** [comment]
Hi @Greggis  -
 Thanks for the update, much appreciated! Do you have a support case number? I want to take a look at the HXTool debug log.

Thanks,
 Elazar

**Comment by Greggis** [comment]
Hi Elazar,

I apologize for the delayed response, but I have been out on vacation.  The support case number is 01409861.  Let me know if you need anything further.  Thank you.

**Comment by Greggis** [comment]
Another thing to add that I discovered.  If I go to Rules/Mange Rules, although I see "no data available in table", I am still able to import a rule that I exported from another controller.  I am still unable to see it in HXTool, but when I go to the controller UI, I see that it imports successfully.

**Comment by B0fH** [comment]
Hi @Greggis  - 
 Thanks! I looked at the ticket and didn't see the HXTool log, just the controller logs. Can you run hxtool.py with the -debug flag and attach the debug log to the ticket?

Thanks,
 Elazar

**Comment by B0fH** [comment]
Hi @Greggis  -
 Is this still an issue?

Thanks,
 Elazar
