### ISSUE TITLE
"failed to create indicator" with HX 5.1.1

### ISSUE THREAD

**Issue by rcarmack1** [fireeye/HXTool#100]
I am running HX 5.1.1, and every attempt to create an indicator presents the message "failed to create indicator".  HXTool version is the newest available, downloaded and installed on 2/21/22.

**Comment by B0fH** [comment]
Hi @rcarmack1 -
 Which user are you using to log in to HXTool with? Does this user have the api_admin or api_analyst role?

Thanks,
 Elazar

**Comment by rcarmack1** [comment]
Thanks for the suggestion - changing the role from admin to ap_admin did the trick.
