### ISSUE TITLE
Jinja2 evalcontextfilter moved

### ISSUE THREAD

**Issue by recluster** [fireeye/HXTool#104]
Hello ,
on the last 3.1 Jinja version (https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0) eval contexfilter moved to pass_context. evalcontextfilter

Flask import of hxtool.py are no longer correct.
`# Flask imports
try:
	from flask import Flask, request, Response, session, redirect, render_template, send_file, g, url_for, abort, Blueprint
	from jinja2 import evalcontextfilter, Markup, escape
except ImportError:
	print("hxtool requires the 'Flask' module, please install it.")
	exit(1)`

**Comment by B0fH** [comment]
Resolved with #105
