### ISSUE TITLE
Create new release or mark 4.7 as broken

### ISSUE THREAD

**Issue by lluked** [fireeye/HXTool#110]
Hi,

I was trying for hours to run release 4.7 and pulling my hair out with it not working. It appears it was not working due to changing dependencies with jinja2 markupsafe and escape and this has been fixed in the master branch. Please can you update the release page to state it is not working to save anyone else the same hassle? or create a new release based on the master?

Thanks
Luke

**Comment by B0fH** [comment]
Hi @lluked -
 This is a great point, let me discuss with @CoderHenrik and get a likely 4.7.1 release out the door.

Thanks,
 Elazar

**Comment by lluked** [comment]
> Hi @lluked - This is a great point, let me discuss with @CoderHenrik and get a likely 4.7.1 release out the door.
> 
> Thanks, Elazar

Hi Elazar,

Thanks for looking into this

Thanks
Luke

**Comment by B0fH** [comment]
Hi @lluked -
 We've branched master and issued a 4.7.1 release.

Thanks,
 Elazar

**Comment by lluked** [comment]
Hi @B0fH

Thanks for the quick turnaround!

Kind Regards
Luke
