### ISSUE TITLE
Enterprise Search > Pending status count ?

### ISSUE THREAD

**Issue by doitnow40** [fireeye/HXTool#122]
Hi,

Q1)
What does the number of "pending" mean in the column in the Enterprise Search Results list?  I read the HX user guide, but I couldn't find anything explaining 'pending' status as an enterprise search result. 
In what cases do you get a 'pending' state, and how do you reduce it?

Thanks.

**Comment by B0fH** [comment]
Hi @doitnow40 -
 Agents in a pending state mean that the job hasn't been received by the agent yet. Usually this means that those agents are offline. However, this can also happen when the concurrent host limit for the host set in question is set too low, and the first chunk of agents that have been tasked have a high number of offline or decommissioned agents.

Thanks,
 Elazar
