### ISSUE TITLE
Cloud hx - hx tool - api - proxy environment

### ISSUE THREAD

**Issue by dannysapple** [fireeye/HXTool#21]
While connecting to cloud hx api, from hx tool from proxied enterprise environment, could not able to reach due to proxy required.
Can you provide an explicit proxy option while connecting, please.

Thank you

**Comment by B0fH** [comment]
Hi @dannysapple  -
 Kindly take a look at [proxy configuration section](https://github.com/fireeye/HXTool/blob/b01080fe6ef6f47fee03ad2b4951d34d45f2777f/README.CONFIG#L25) of README.CONFIG. This provides the syntax required for conf.json to specify a proxy that HXTool will use for all communications with the controller.

Thanks,
 Elazar
