### ISSUE TITLE
Unable to edit the Platform in the Rule management

### ISSUE THREAD

**Issue by xambroz** [fireeye/HXTool#23]
Hello,
When creating the rule, by default the rule has all the platforms - Win, MacOS, Linux
![image](https://user-images.githubusercontent.com/723625/95214031-bfb7bd00-07ef-11eb-93ab-f5ad9b006fd2.png)

Then if you edit the rule and save it (without changing the Patform, which is set to ALL), it removes the Linux platform:
![image](https://user-images.githubusercontent.com/723625/95214197-efff5b80-07ef-11eb-8a47-b5b207e15cd4.png)

Then it is possible to switch exclusively to Win, Linux or MacOS. 
Setting it to "ALL" will always result only in "Win+MacOS" being set.
It is not possible to get the combinations "Linux+MacOS" or "Win+Linux"

Usual user experience is that with the CTRL you would be able to click multiple platforms not just one.
At least saving without changes to platform should preserve the original state and setting it to "ALL" should result in all the platforms (including Linux) to be used.

Thank you
Michal Ambroz

**Comment by xambroz** [comment]
Workaround:
If you accidentally edit the rule and remove the linux platform from all the platforms, then clone the rule and remove the original - the clone will be again set to all 3 platforms.

**Comment by B0fH** [comment]
Hi @xambroz  -
 Thanks for reporting this, it is indeed a bug. It looks like we're missing Linux from the list [here](https://github.com/fireeye/HXTool/blob/b01080fe6ef6f47fee03ad2b4951d34d45f2777f/hxtool_api.py#L1012). I'll go ahead and get that fixed.

Thanks,
 Elazar
