### ISSUE TITLE
cant add an indicator in HXtool 4.5.1.2

### ISSUE THREAD

**Issue by kalfard** [fireeye/HXTool#29]
Hi,

Were using HX 5.0.1.917137 , with HXtool 4.5.1.2 and we have created and enabled API account with admin rights
unfortunately we cannot create a custom indicator and were getting a "failed to create indicator" error

also we have also enabled the background processing settings

Thanks in advance.

Regards,
Khaled

**Comment by B0fH** [comment]
Hi @kalfard -
 Unfortunately, HXTool 4.5.1.2 has a bug that prevents it from working with HX 5.0. To resolve this, you can either:
a) replace hx_lib.py with the one from master [hx_lib.py](https://raw.githubusercontent.com/fireeye/HXTool/master/hx_lib.py) and restart HXTool
b) Upgrade HXTool with a snapshot of master.

Thanks,
 Elazar

**Comment by kalfard** [comment]
Thanks its working now !
