### ISSUE TITLE
UI Rendering issue for HXTool 4.5.1.2 on Resolution 1600X900

### ISSUE THREAD

**Issue by davidbarberis** [fireeye/HXTool#3]
![McKinsey_HX 4 5 1 2_Res1600X900 April 15 2020](https://user-images.githubusercontent.com/63733519/79353609-45c20d80-7f09-11ea-9724-78ef93d4b42e.jpg)

Ran into a fairly minor UI rendering issue (Resolution 1600X900) via RDP for HXTool version 4.5.1.2 and had to use the browser Zoom In/Out to correct:

**Comment by B0fH** [comment]
Fixed in 4.6 by https://github.com/fireeye/HXTool/commit/c1520439c8e314afe16cd96962fcfc26032ce74f
