### ISSUE TITLE
HX API 5.0 problem with HXTool? 

### ISSUE THREAD

**Issue by mathurin68** [fireeye/HXTool#30]
We upgraded one of our HX controllers to 5.0
![image](https://user-images.githubusercontent.com/5932961/96733218-3378ce80-1387-11eb-8253-05809d9440f1.png)

but now certain features don't seem to be available, for example, if I try to 'manage rules' 
![image](https://user-images.githubusercontent.com/5932961/96733439-733fb600-1387-11eb-80eb-4e362a888662.png)

I get a 'DataTables warning: table id=iocTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7'   AND it looks like some of the main dashboard isn't populating.  

The other controller we have still at 4.9 seems to be working fine.  

A lot of the new tools and addons in 5.0 look really promising so I do have my fingers crossed about the next version of HXTool (no pressure, no pressure, no pressure!)

**Comment by B0fH** [comment]
Hi @mathurin68 -
 Unfortunately, HXTool 4.5.1.2 has a bug that prevents it from working with HX 5.0. To resolve this, you can either:
a) replace hx_lib.py with the one from master [hx_lib.py](https://raw.githubusercontent.com/fireeye/HXTool/master/hx_lib.py) and restart HXTool
b) Upgrade HXTool altogether with a snapshot of [master](https://github.com/fireeye/HXTool/archive/master.zip).

Thanks,
Elazar

**Comment by mathurin68** [comment]
@B0fH  Thank you so much for the fast response! Upgraded to 4.6 and boom it works!
