### ISSUE TITLE
[Feature request] Bulk .ioc indicator import

### ISSUE THREAD

**Issue by wikijm** [fireeye/HXTool#47]
Hi,

Is it possible to add a functionality to bulk import multiple .ioc files (indicators previously generated by HXTool)?
I would like to 'train' my detections rules to a principal console, then export them and imported to other HX consoles.

If there is a workaround, don't hesitate to provide it here, no need to have an implementation into the webconsole, a Python script is enough 😉 

Regards,
WikiJM

**Comment by B0fH** [comment]
Hi @wikijm -
 You can do this today in HXTool 4.6, when importing rules/IOCs, simply select multiple files.

Thanks,
 Elazar

**Comment by wikijm** [comment]
Hi Elazar,

Oh you're right, I see that on the changelog of the last release.
Thank you for your kind and effective answer 😃 

Regards,
WikiJM
