### ISSUE TITLE
4.7-pre using mongodb and 'Audit Explorer' 

### ISSUE THREAD

**Issue by mathurin68** [fireeye/HXTool#53]
If I want to start to use the audit explorer... 
"The upcoming Audit Explorer feature (in HXTool master) leverages the MongoDB task module. Essentially, you need to configure HXTool to use MongoDB - see README.config - and then run any bulk acquisition script with the task profile set to one configured to use MongoDB. Once the acquisition is complete, you'll see the audits listed under Manage Audits, hit Explore to slice and dice the data under Audit Explorer."
And I see under readme.config

```
8. "db" (right now only for MongoDB usage)
	- "type" : "string; required; only acceptable value is mongodb"
	- "host" : "string; required; IP or FQDN of the database server"
	- "port" : "integer; optional; the port with which to contact the database server on, defaults vary by database type"
	- "user" : "string; required; username with which to authenticate with"
	- "password" : "string; required; password with which to authenticate with"
	- "auth_source" : "string; required; MongoDB only, authentication source database"
	- "auth_mechanism" : "string; optional; MongoDB only, the authentication mechanism to use, defaults to SCRAM-SHA-256"
	- "db_name" : "string; optional; The name of the database to use, defaults to hxtool"
```

...but in my config.json there isn't a "db" section, is it OK to add one or should I just wait?

**Comment by B0fH** [comment]
Hi @mathurin68  -
 Yup, thats correct. Simply append a db section on your conf.json, like so:
 
 
![image](https://user-images.githubusercontent.com/1335037/103312662-bce1f800-49eb-11eb-8ef1-fc83be538316.png)

(snipped most of the config content for brevity)

Just make sure your config file is valid JSON once you add the section.

Thanks,
 Elazar

**Comment by mathurin68** [comment]
FINALLY, getting a chance to come back around to this. 
Did something happen to the documentation on this? I don't see it anywhere on the website and haha I can't find where I originally ready about it.

**Comment by B0fH** [comment]
Hi @mathurin68 -
 Section 8 of [README.CONFIG](https://github.com/fireeye/HXTool/blob/master/README.CONFIG) should have you covered. As for setting up Mongo itself, I'd refer to the Mongo documentation: https://docs.mongodb.com/manual/installation/

Thanks,
 Elazar

**Comment by mathurin68** [comment]
Ah...OK!  Thank you, I'll play around with it!

**Comment by mathurin68** [comment]
Moving to a new question since I'm further along....
