### ISSUE TITLE
Using PAC files instead of directly using password

### ISSUE THREAD

**Issue by don-boss670** [fireeye/HXTool#66]
Can u please update the config file proxy section using PAC file for authentication instead of using direct password.

**Comment by B0fH** [comment]
Hi @don-boss670 -
 Does your proxy require authentication, even when using a PAC file? If so, then this might not be the best route to solve your issue as the PAC module is still going to need those credentials stored somewhere - it won't be able to leverage your existing Windows session to pass through credentials.

Thanks,
 Elazar

**Comment by B0fH** [comment]
Hi @don-boss670 -
 PAC support has been committed. Closing this.

Thanks,
 Elazar
