### ISSUE TITLE
Alerts tab, can we show one of each alert? 

### ISSUE THREAD

**Issue by mathurin68** [fireeye/HXTool#76]
At the moment in HXTool the 'Alerts' section seems to show every single time an alert fires, is there any way to show each alert one time for each host?  Maybe a separate column for how many times it's fired. 

It would make it easier to prioritize and work on alerts directly from hxtool.  

Thank you!

**Comment by B0fH** [comment]
Hi @mathurin68  -
 So the Endpoint Security console actually does just that: it shows alerts in alert groups, as opposed to every single alert. You are correct that HXTool shows all alerts as opposed to the groups. Looping in @CoderHenrik to get his take on setting up a separate grid that shows the alert groups and their associated alert counts.

Thanks, 
 Ekazar

**Comment by mathurin68** [comment]
Hah, I almost everything else in hxtool... just being lazy!  Thank you and closing.
