### ISSUE TITLE
Date range Filter of Alerts page

### ISSUE THREAD

**Issue by romio1212** [fireeye/HXTool#81]
Hi,

 

I am using HXTOOL 4.8pre.

I applied the "MONTH" or "QUARTER" or "HALF-YEAR" or 'YEAR" filters in the alert page of HXTOOL and clicked the Refresh button. However, these results do not display recent alerts. Are there any issues? ?

 For example, if the MONTH filter is used, "From 2021-05-30 to 2021-06-29" is specified. When the refresh button is clicked, the date of the last alert in the output list is displayed only up to 21-06-13, not 21-06-29.

but, WEEKLY and DAILY filter is normal. 

When I checked the Exported "excel file", it seems that the number of Alerts is output up to 1000. I think this is the cause. If this is true, can you increase this number?

​

 

Thanks.

**Comment by B0fH** [comment]
Hi @romio1212  -
 The 1K alert limit is by design to prevent HXTool from timing out when loading many alerts from loaded controllers. We can look into a configuration option to increase this value.

Thanks,
 Elazar

Thanks,
 Elazar

**Comment by romio1212** [comment]
> Hi @romio1212 -
> The 1K alert limit is by design to prevent HXTool from timing out when loading many alerts from loaded controllers. We can look into a configuration option to increase this value.
> 
> Thanks,
> Elazar
> 
> Thanks,
> Elazar

Hi,
How can I change this value ?  
Which source files do I need to modify?

Thanks.

**Comment by B0fH** [comment]
Hi @romio1212 -
 Under templates/ht_alert.html, there's several API calls to /api/v1/datatable_alerts_full with a limit parameter of 1000, for example https://github.com/fireeye/HXTool/blob/e3ab2767d77e029b5e6d4755df78f624b445f2d1/templates/ht_alert.html#L48. You can change the limit value or remove it altogether and restart HXTool.

Thanks,
 Elazar
