### ISSUE TITLE
The Negate capability for IOC creation causes error

### ISSUE THREAD

**Issue by lumenterry** [fireeye/HXTool#84]
We have been using HXTool from the start and do really like it.  Primarily we use it to create Custom IOCs as it offers better capabilities.  Just noticed that the Negate capability when used with IOC Operators causes an Error when the Rule is submitted with the Negate box checked.  Remove the check on Negate and the rule submits fine.

I have used Negate many times over the years developing IOCs, so not sure why we are having an issue now.

Submit Error is general:  "failed to create indicator conditions, check your conditions"

While we are currently running version HXTool 4.7, however, I also went back and tried it on previous versions that I know use to work.  Same Error.  This makes me think it is HX version related.  We are running HX 5.1 on all of our HX's and this Error happens on all of them.

**Comment by B0fH** [comment]
Hi @lumenterry -
 Does you condition have a single test with the negate checked? If so, this is by design to prevent FP storms: to wit, '*not* process equals powershell.exe' matches everything else all the time.

Thanks,
 Elazar

**Comment by lumenterry** [comment]
Sure enough, thats it..  thanks...

**Comment by B0fH** [comment]
Thanks for the update!
