### ISSUE TITLE
4.8-Pre on Centos can't add background processing credentials

### ISSUE THREAD

**Issue by mathurin68** [fireeye/HXTool#85]
Can't seem to save the 'Background Credentials' to hxtool.  

Working on Centos Server -
CentOS Linux release 7.9.2009 (Core)
python 3.8 (virtualenv)
HXTool 4.8-pre

Getting the following error trying to set the Background Processing Credentials...
`keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.`

And keyring appears to be installed ...
```
Requirement already satisfied: cffi>=1.12 in ./venv_fireeye/lib/python3.8/site-packages (from cryptography>=2.0->SecretStorage>=3.2; sys_platform == "linux"->keyring->-r requirements.txt (line 6)) (1.14.6)
Requirement already satisfied: pycparser in ./venv_fireeye/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage>=3.2; sys_platform == "linux"->keyring->-r requirements.txt (line 6)) (2.20)
```

Is there anything else I can do?

**Comment by mathurin68** [comment]
I don't know, it seems to be because I'm on a headless linux system?  And no idea how to install one of the 3rd party packages.  Do I just run pip install keyring.cryptfile?  We've even installed gnome-keyring... same errors, but I have no idea what I'm doing.

**Comment by B0fH** [comment]
Hi @mathurin68 -
 You are correct in that keyring requires some additional steps on headless systems, kindly take a look at https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems. 

As you noted, cryptfile is an alternative backend if you're unable to get gnome-keyring to work: https://pypi.org/project/keyrings.cryptfile/ Just 'pip install keyrings.cryptfile' and restart HXTool.

Thanks,
 Elazar

**Comment by mathurin68** [comment]
The error I get on keyrings.cryptfile-- 

```
  File "/opt/hxtool/venv_fireeye/lib64/python3.8/site-packages/keyrings/cryptfile/file.py", line 119, in _init_file
    self._keyring_key = self._get_new_password()
  File "/opt/hxtool/venv_fireeye/lib64/python3.8/site-packages/keyrings/cryptfile/file.py", line 55, in _get_new_password
    password = getpass.getpass("Please set a password for your new keyring: ")
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/getpass.py", line 91, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/getpass.py", line 126, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/getpass.py", line 148, in _raw_input
    raise EOFError
EOFError
```
...I can't seem to find a solution to storing this password somewhere.  This, https://pypi.org/project/keyrings.cryptfile/ didn't seem to offer any workable solutions, but, again, I have no idea what I'm doing. 

Definitely not ideal, but keyrings.alt does work.

**Comment by B0fH** [comment]
Hi @mathurin68  -
 keyrings.cryptfile requires a password to secure the keyring, which is what you're running into. keyrings.alt is certainly an alternative but not optimal. At this point, I think I'm going to build a fallback backend that mimics the previous behavior where we used a dynamically generated key stored in a file to encrypt the password - not optimal either, but at least it will make it seamless on headless systems.

Thanks,
 Elazar

**Comment by mathurin68** [comment]
I'll close it, thank you so much!
