### ISSUE TITLE
Hivenightmare Detection in FY HX

### ISSUE THREAD

**Issue by don-boss670** [fireeye/HXTool#86]
Need to create a behavior based HX rule logic for "any process other than vssadmin and vssvc trying to read sensitive registry hive’s SAM, SYSTEM and SECURITY"

**Comment by don-boss670** [comment]
Please comment on this...

**Comment by B0fH** [comment]
Hi @don-boss670 -
 The FireEye Endpoint Security agent doesn't monitor file or registry read activity. That said, you could create a processEvent indicator that looks for either of those three terms in the command line where the actor process does not match vssadmin or vssvc. For example:

![image](https://user-images.githubusercontent.com/1335037/132743024-65b73cb6-192a-4afd-b89f-1f495b4bf091.png)

Thanks,
 Elazar
