### ISSUE TITLE
Multi File Acquisition

### ISSUE THREAD

**Issue by blogctechz** [fireeye/HXTool#87]
Hi,

Just a question regarding the Multi-File Acquisition feature. **Is it possible to specify different File Paths at the same time**** while acquiring the file ?.  Or we can just specify the single path.

**Comment by B0fH** [comment]
Hi @blogctechz  -
 Not within the same instance of the multi-file audit. You have one of two options here:
1. Specify a base path for Path, and then use PathRegex to filter across multiple sub-paths
2. Specify multiple, separate multifile-acquisition modules within the same script

Thanks,
 Elazar
