### ISSUE TITLE
BulkAcquisition ID not Creating

### ISSUE THREAD

**Issue by blogctechz** [fireeye/HXTool#89]
Hi Team,
While acquiring the Bulk acquisition, ID is not creating under the folder "HXTOOL_ROOT\bulkdownload\HX_HOSTNAME\BULK_ACQUISITION_ID" which contains the acquired data.  Also Download button is faded and cant download data from the web UI.

Any help?

**Comment by B0fH** [comment]
Hi @blogctechz -
 Did you set the background credentials(under the HXTool Settings menu) that the HXTool scheduler needs to run the job?

Thanks,
 Elazar

**Comment by B0fH** [comment]
Hi @blogctechz  -
 Is this still an issue?
