### ISSUE TITLE
Jquery upgrade on FireEye HXTool

### ISSUE THREAD

**Issue by dthschyt3** [fireeye/HXTool#90]
Currently there's a vulnerability related to jQuery v3.2.1, so we've decided to upgrade the jQuery by following the steps below:

a)	Download https://code.jquery.com/jquery-3.6.0.min.js and place it in <hxtool home directory>/static/js/
b)	Open <hxtool home directory>/templates/layout.html and change line 15 to load the new version instead of the old version
c)	Restart HXTool

Unfortunately, this didn't work and we're getting an "Invalid profile ID" when we try to login to HXTool.

Anyone has any idea on how we can upgrade the jQuery version without causing any issues?

**Comment by B0fH** [comment]
Hi @dthschyt3 -
 Let me look into this.

Thanks,
 Elazar

**Comment by B0fH** [comment]
Hi @dthschyt3 -
 I've merged https://github.com/fireeye/HXTool/pull/91 which upgrades JQuery to 3.6.0. You can grab ht_login.html and layout.html, replace them in your existing HXTool instance and restart HXTool.

Thanks,
 Elazar

**Comment by dthschyt3** [comment]
Hi Elazar,

It works now. Thank you very much.

Regards,
Harold
