### ISSUE TITLE
HOW to export IOC details by using HX tool

### ISSUE THREAD

**Issue by FinnChen1** [fireeye/HXTool#97]
As the picture below in HX web IOC I can see the details of MD5 equal 7a0dfc5353ff6de7de0208a29fa2ffc9

but in HX tool web the csv I already export can not find any information about MD5

so how should I do if I want to export the details of the IOC rule ?

I try to use HX tool version 4.6 4.7 pre 4.8 face the same problem

![HX tool IOC](https://user-images.githubusercontent.com/99307981/153119135-0c5a3698-18ea-4a56-9807-b84fca24ce55.JPG)
![HX WEB IOC](https://user-images.githubusercontent.com/99307981/153119138-ff24e134-51af-431f-8a6b-8f18d56660d0.jpg)

**Comment by B0fH** [comment]
Hi @FinnChen1 -
 I'm unable to replicate this using the same indicator. Do you see any errors in the console that HXTool is running in? Additionally, what role does the user you're logging in to HXTool with have?

Thanks,
 Elazar

**Comment by FinnChen1** [comment]
I use role : Admin  create indicator on HX web console  and use role : Admin export indicator on HX tool, and no error show on the HX tool. I also try to use role:Admin import Rules by txt on HX tool but it doesn't work the role can not see on the hxtool. 
I also try another way to create new rule on HX tool and it doesn't work again and show failed to create indicator.
![image](https://user-images.githubusercontent.com/99307981/153328619-b9bb57e6-bed1-4643-9b2a-9cb1357738a7.png)

**Comment by FinnChen1** [comment]
Hi Elazar
I already follow the procedure you gave and it work successfully!

Thanks!
