### ISSUE TITLE
ImageLoad Event Mapping Bug(?)

### ISSUE THREAD

**Issue by BIitzkrieg** [fireeye/HXTool#98]
When Importing an Image Load Event in OpenIOC format, HXTool accepts and creates the rule with the following indicator object logic:
`<Indicator operator="AND" id="b8a1abcd-1a69-16c7-4da4-f9fc3c6da5d7">
				<IndicatorItem id="e3e70682-c209-4cac-629f-6fbed82c07cd" condition="ends-with" preserve-case="false" negate="false">
					<Context document="imageLoadEvent" search="imageLoadEvent/processPath" type="event" />
					<Content type="string">\spoolsv.exe</Content>
				</IndicatorItem>`
See:
[https://imgur.com/KWFtUYy](url)

However processPath does not appear to be a valid mapping for Image Load Events in HXTool. HX separates the process and process path to separate fields - just "Process" and "Path" - so writing a rule that looks for a process name at the end of the path wont work, since image load events dont capture the process in the path object. It appears process events do, however.
[https://imgur.com/a/OmHIB3a](url)

If i try and edit the rule in HXTool, it simply returns an empty logic builder:
[https://imgur.com/Jqzv0LA](url)

I wish the Process Information for Image Load Events captured the process name in the full path similar to process events, but either way it appears there is no way to specify the process path in HXTool for Image Load Events.

**Comment by B0fH** [comment]
Hi @BIitzkrieg -
 Thanks for the note, this is indeed a bug due to a missing processPath token in static/eventbuffer.json for imageLoadEvent. I've merged a PR which resolves this. You can simply replace your eventbuffer.json with the one from here: https://raw.githubusercontent.com/fireeye/HXTool/master/static/eventbuffer.json and restart HXTool.

Thanks,
 Elazar

**Comment by BIitzkrieg** [comment]
> Hi @BIitzkrieg - Thanks for the note, this is indeed a bug due to a missing processPath token in static/eventbuffer.json for imageLoadEvent. I've merged a PR which resolves this. You can simply replace your eventbuffer.json with the one from here: https://raw.githubusercontent.com/fireeye/HXTool/master/static/eventbuffer.json and restart HXTool.
> 
> Thanks, Elazar

Thanks Elazar, this works. On a separate note, im putting in a case with fire eye to hopefully modify the way the HX agent logs process info for image load events... this would be more uniform in my opinion. We write analytics  based on sysmon with SIGMA, and convert the analytics using sigmac (uncoder.io for a nice web frontend). The way HX currently implements this event logging wouldn't allow us to easily convert analytics that rely on the process path ending with the process name... hope that makes sense. 
Examples:
(Process Events)
Process Name:
appidpolicyconverter.exe
Path:
C:\Windows\System32\appidpolicyconverter.exe

==================================
(Image Load Events)
Process:
conhost.exe
Path:
C:\Windows\System32

(What I would like for image load events):
Process Name:
conhost.exe
Path:
C:\Windows\System32\conhost.exe

**Comment by B0fH** [comment]
Hi @BIitzkrieg -
Thanks for the heads up on the inconsistency, I'll follow up internally.

Thanks,
 Elazar
